In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("safrin03/predictive-analytics-for-customer-churn-dataset")

print("Path to dataset files:", path)

ModuleNotFoundError: No module named 'kagglehub'

In [84]:
from pathlib import Path
import shutil

source = Path(path)
destination = Path("../data/raw")

destination.mkdir(parents=True, exist_ok=True)

for file in source.iterdir():
    if file.is_file():
        shutil.move(file, destination)

print("Done!")

Done!

In [85]:
import pandas as pd 
data_path = "../data/raw"

train = pd.read_csv(f"{data_path}/train.csv")
test = pd.read_csv(f"{data_path}/test.csv")

In [86]:
len(train), len(test)

(243787, 104480)

In [87]:
# We do not touch the test set.

In [88]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243787 entries, 0 to 243786
Data columns (total 21 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   AccountAge                243787 non-null  int64
 1   MonthlyCharges            243787 non-null  float64
 2   TotalCharges              243787 non-null  float64
 3   SubscriptionType          243787 non-null  object
 4   PaymentMethod             243787 non-null  object
 5   PaperlessBilling          243787 non-null  object
 6   ContentType               243787 non-null  object
 7   MultiDeviceAccess         243787 non-null  object
 8   DeviceRegistered          243787 non-null  object
 9   ViewingHoursPerWeek       243787 non-null  float64
 10  AverageViewingDuration    243787 non-null  float64
 11  ContentDownloadsPerMonth  243787 non-null  int64
 12  GenrePreference           243787 non-null  object
 13  UserRating                243787 non-null  float64
 14  SupportTicketsPerMonth    243787 non-null  int64
 15  Gender                    243787 non-null  object
 16  WatchlistSize             243787 non-null  int64
 17  ParentalControl           243787 non-null  object
 18  SubtitlesEnabled          243787 non-null  object
 19  CustomerID                243787 non-null  object
 20  Churn                     243787 non-null  int64
dtypes: float64(5), int64(5), object(11)
memory usage: 39.1+ MB

In [89]:
train.head().T

,0,1,2,3,4
AccountAge,20,57,73,32,57
MonthlyCharges,11.055215,5.175208,12.106657,7.263743,16.953078
TotalCharges,221.104302,294.986882,883.785952,232.439774,966.325422
SubscriptionType,Premium,Basic,Basic,Basic,Premium
PaymentMethod,Mailed check,Credit card,Mailed check,Electronic check,Electronic check
PaperlessBilling,No,Yes,Yes,No,Yes
ContentType,Both,Movies,Movies,TV Shows,TV Shows
MultiDeviceAccess,No,No,No,No,No
DeviceRegistered,Mobile,Tablet,Computer,Tablet,TV
ViewingHoursPerWeek,36.758104,32.450568,7.39516,27.960389,20.083397
AverageViewingDuration,63.531377,25.725595,57.364061,131.537507,45.356653
ContentDownloadsPerMonth,10,18,23,30,20
GenrePreference,Sci-Fi,Action,Fantasy,Drama,Comedy
UserRating,2.176498,3.478632,4.238824,4.276013,3.61617
SupportTicketsPerMonth,4,8,6,2,4
Gender,Male,Male,Male,Male,Female
WatchlistSize,3,23,1,24,0
ParentalControl,No,No,Yes,Yes,No
SubtitlesEnabled,No,Yes,Yes,Yes,No
CustomerID,CB6SXPNVZA,S7R2G87O09,EASDC20BDT,NPF69NT69N,4LGYPK7VOL
Churn,0,0,0,0,0

In [90]:
# Let's see if there are any missing values.

In [91]:
train.isna().sum() # Good, there are not

AccountAge                  0
MonthlyCharges              0
TotalCharges                0
SubscriptionType            0
PaymentMethod               0
PaperlessBilling            0
ContentType                 0
MultiDeviceAccess           0
DeviceRegistered            0
ViewingHoursPerWeek         0
AverageViewingDuration      0
ContentDownloadsPerMonth    0
GenrePreference             0
UserRating                  0
SupportTicketsPerMonth      0
Gender                      0
WatchlistSize               0
ParentalControl             0
SubtitlesEnabled            0
CustomerID                  0
Churn                       0
dtype: int64

In [92]:
train.describe().T

,count,mean,std,min,25%,50%,75%,max
AccountAge,243787.0,60.083758,34.285143,1.000000,30.000000,60.000000,90.000000,119.000000
MonthlyCharges,243787.0,12.490695,4.327615,4.990062,8.738543,12.495555,16.238160,19.989957
TotalCharges,243787.0,750.741017,523.073273,4.991154,329.147027,649.878487,1089.317362,2378.723844
ViewingHoursPerWeek,243787.0,20.502179,11.243753,1.000065,10.763953,20.523116,30.219396,39.999723
AverageViewingDuration,243787.0,92.264061,50.505243,5.000547,48.382395,92.249992,135.908048,179.999275
ContentDownloadsPerMonth,243787.0,24.503513,14.421174,0.000000,12.000000,24.000000,37.000000,49.000000
UserRating,243787.0,3.002713,1.155259,1.000007,2.000853,3.002261,4.002157,4.999989
SupportTicketsPerMonth,243787.0,4.504186,2.872548,0.000000,2.000000,4.000000,7.000000,9.000000
WatchlistSize,243787.0,12.018508,7.193034,0.000000,6.000000,12.000000,18.000000,24.000000
Churn,243787.0,0.181232,0.385211,0.000000,0.000000,0.000000,0.000000,1.000000

In [93]:
# We can drop CustomerID since it does not carry any information.
# Before making any changes, let's copy the dataframe.

In [94]:
train_ = train.copy()

In [95]:
train_ = train_.drop("CustomerID", axis=1)

In [96]:
train_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243787 entries, 0 to 243786
Data columns (total 20 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   AccountAge                243787 non-null  int64
 1   MonthlyCharges            243787 non-null  float64
 2   TotalCharges              243787 non-null  float64
 3   SubscriptionType          243787 non-null  object
 4   PaymentMethod             243787 non-null  object
 5   PaperlessBilling          243787 non-null  object
 6   ContentType               243787 non-null  object
 7   MultiDeviceAccess         243787 non-null  object
 8   DeviceRegistered          243787 non-null  object
 9   ViewingHoursPerWeek       243787 non-null  float64
 10  AverageViewingDuration    243787 non-null  float64
 11  ContentDownloadsPerMonth  243787 non-null  int64
 12  GenrePreference           243787 non-null  object
 13  UserRating                243787 non-null  float64
 14  SupportTicketsPerMonth    243787 non-null  int64
 15  Gender                    243787 non-null  object
 16  WatchlistSize             243787 non-null  int64
 17  ParentalControl           243787 non-null  object
 18  SubtitlesEnabled          243787 non-null  object
 19  Churn                     243787 non-null  int64
dtypes: float64(5), int64(5), object(10)
memory usage: 37.2+ MB

In [97]:
# Let's see if there are any duplicates

In [98]:
train_.duplicated().sum() # Good, there are not.

np.int64(0)

In [99]:
train_.head()

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,GenrePreference,UserRating,SupportTicketsPerMonth,Gender,WatchlistSize,ParentalControl,SubtitlesEnabled,Churn
0,20,11.055215,221.104302,Premium,Mailed check,No,Both,No,Mobile,36.758104,63.531377,10,Sci-Fi,2.176498,4,Male,3,No,No,0
1,57,5.175208,294.986882,Basic,Credit card,Yes,Movies,No,Tablet,32.450568,25.725595,18,Action,3.478632,8,Male,23,No,Yes,0
2,73,12.106657,883.785952,Basic,Mailed check,Yes,Movies,No,Computer,7.395160,57.364061,23,Fantasy,4.238824,6,Male,1,Yes,Yes,0
3,32,7.263743,232.439774,Basic,Electronic check,No,TV Shows,No,Tablet,27.960389,131.537507,30,Drama,4.276013,2,Male,24,Yes,Yes,0
4,57,16.953078,966.325422,Premium,Electronic check,Yes,TV Shows,No,TV,20.083397,45.356653,20,Comedy,3.616170,4,Female,0,No,No,0

In [100]:
# Churn feature must be object, let's turn it.

In [101]:
train_["Churn"] = train_["Churn"].astype("object")

In [102]:
train_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243787 entries, 0 to 243786
Data columns (total 20 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   AccountAge                243787 non-null  int64
 1   MonthlyCharges            243787 non-null  float64
 2   TotalCharges              243787 non-null  float64
 3   SubscriptionType          243787 non-null  object
 4   PaymentMethod             243787 non-null  object
 5   PaperlessBilling          243787 non-null  object
 6   ContentType               243787 non-null  object
 7   MultiDeviceAccess         243787 non-null  object
 8   DeviceRegistered          243787 non-null  object
 9   ViewingHoursPerWeek       243787 non-null  float64
 10  AverageViewingDuration    243787 non-null  float64
 11  ContentDownloadsPerMonth  243787 non-null  int64
 12  GenrePreference           243787 non-null  object
 13  UserRating                243787 non-null  float64
 14  SupportTicketsPerMonth    243787 non-null  int64
 15  Gender                    243787 non-null  object
 16  WatchlistSize             243787 non-null  int64
 17  ParentalControl           243787 non-null  object
 18  SubtitlesEnabled          243787 non-null  object
 19  Churn                     243787 non-null  object
dtypes: float64(5), int64(4), object(11)
memory usage: 37.2+ MB

In [103]:
train_.nunique().sort_values()

MultiDeviceAccess                2
PaperlessBilling                 2
Gender                           2
ParentalControl                  2
SubtitlesEnabled                 2
Churn                            2
ContentType                      3
SubscriptionType                 3
DeviceRegistered                 4
PaymentMethod                    4
GenrePreference                  5
SupportTicketsPerMonth          10
WatchlistSize                   25
ContentDownloadsPerMonth        50
AccountAge                     119
TotalCharges                243787
UserRating                  243787
AverageViewingDuration      243787
ViewingHoursPerWeek         243787
MonthlyCharges              243787
dtype: int64

In [104]:
train_["Churn"].value_counts(normalize=True) # The dataset is highly imbalanced. (0's dominates 1's)

Churn
0    0.818768
1    0.181232
Name: proportion, dtype: float64

In [105]:
(train_ == "?").sum()

AccountAge                  0
MonthlyCharges              0
TotalCharges                0
SubscriptionType            0
PaymentMethod               0
PaperlessBilling            0
ContentType                 0
MultiDeviceAccess           0
DeviceRegistered            0
ViewingHoursPerWeek         0
AverageViewingDuration      0
ContentDownloadsPerMonth    0
GenrePreference             0
UserRating                  0
SupportTicketsPerMonth      0
Gender                      0
WatchlistSize               0
ParentalControl             0
SubtitlesEnabled            0
Churn                       0
dtype: int64

In [106]:
train_.columns

Index(['AccountAge', 'MonthlyCharges', 'TotalCharges', 'SubscriptionType',
       'PaymentMethod', 'PaperlessBilling', 'ContentType', 'MultiDeviceAccess',
       'DeviceRegistered', 'ViewingHoursPerWeek', 'AverageViewingDuration',
       'ContentDownloadsPerMonth', 'GenrePreference', 'UserRating',
       'SupportTicketsPerMonth', 'Gender', 'WatchlistSize', 'ParentalControl',
       'SubtitlesEnabled', 'Churn'],
      dtype='object')

In [107]:
# Let's save the cleaned data.

In [109]:
dest = "../data/processed/train.csv"
train_.to_csv(dest, header=True, index=False)